import { OfficialMetric, ProcessingDateSnapshot, EvidenceSource, CorrectionEntry, CitizenCase } from '@/types';

export const OFFICIAL_METRICS: Record<string, OfficialMetric> = {
  non_irish_employments: {
    id: 'cso_non_irish_emp_2024',
    metric: 'Employments held by non-Irish nationals',
    value: 697219,
    displayValue: '697,219',
    unit: 'employments',
    period: '2024',
    population_definition: 'All employments recorded in the CSO dataset held by individuals of non-Irish nationality.',
    source_organisation: 'Central Statistics Office',
    source_title: 'Business in Ireland 2025 — Labour Market and Social Sustainability (Labour Supply)',
    source_url: 'https://www.cso.ie/',
    publication_date: '2025-06-15',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'CSO records non-Irish nationality, not non-EU. Does not indicate visa or permit type.',
  },
  non_irish_share: {
    id: 'cso_non_irish_share_2024',
    metric: 'Share of total employments held by non-Irish nationals',
    value: 27.5,
    displayValue: '27.5%',
    unit: 'percent',
    period: '2024',
    population_definition: 'Non-Irish nationals as a percentage of total employments/employees in the CSO enterprise dataset.',
    source_organisation: 'Central Statistics Office',
    source_title: 'Business in Ireland 2025 — Labour Market and Social Sustainability',
    source_url: 'https://www.cso.ie/',
    publication_date: '2025-06-15',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Reflects 27.5% of all active payroll employments in Ireland in 2024.',
  },
  employment_growth_share: {
    id: 'cso_emp_growth_share_2019_2024',
    metric: 'Share of net employment growth (2019–2024) attributable to non-Irish nationals',
    value: 61.4,
    displayValue: '61.4%',
    unit: 'percent of growth',
    period: '2019–2024',
    population_definition: 'Increase of 218,261 non-Irish employments out of 355,332 total net new employments created in Ireland.',
    source_organisation: 'Central Statistics Office',
    source_title: 'Business in Ireland 2025 — Labour Market and Social Sustainability',
    source_url: 'https://www.cso.ie/',
    publication_date: '2025-06-15',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Over 6 in 10 net new jobs added to the Irish economy between 2019 and 2024 were filled by non-Irish workers.',
  },
  nursing_intl_share: {
    id: 'doh_nurses_intl_first_qual_2024',
    metric: 'Share of practising nurses with first qualification outside Ireland',
    value: 54.0,
    displayValue: '54.0%',
    unit: 'percent',
    period: '2024',
    population_definition: 'Total 76,558 practising nurses; 54.0% received their primary nursing qualification outside Ireland. Top countries: India, UK, Philippines.',
    source_organisation: 'Department of Health',
    source_title: 'National Healthcare Statistics 2025 (Reference Year 2024)',
    source_url: 'https://www.gov.ie/en/organisation/department-of-health/',
    publication_date: '2025-07-20',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Exact phrasing: "obtained their first nursing qualification outside Ireland". Includes UK and EU-trained nurses.',
  },
  physician_intl_share: {
    id: 'doh_physicians_intl_first_qual_2024',
    metric: 'Share of practising physicians with first medical qualification outside Ireland',
    value: 41.3,
    displayValue: '41.3%',
    unit: 'percent',
    period: '2024',
    population_definition: 'Total 20,961 practising physicians; 41.3% obtained their first medical degree outside Ireland. Top countries: Pakistan, Sudan, UK.',
    source_organisation: 'Department of Health',
    source_title: 'National Healthcare Statistics 2025 (Reference Year 2024)',
    source_url: 'https://www.gov.ie/en/organisation/department-of-health/',
    publication_date: '2025-07-20',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Exact phrasing: "obtained their first medical qualification outside Ireland".',
  },
  indian_workforce_health: {
    id: 'cso_indian_health_share_2024',
    metric: 'Indian nationals in Human Health & Social Work',
    value: 32.2,
    displayValue: '32.2%',
    unit: 'percent of Indian employments',
    period: '2024',
    population_definition: 'Indian nationals represent 3.1% of all employees, 8.8% in ICT, and 6.9% in Health. Nearly one-third (32.2%) of all employments held by Indian nationals are in Health & Social Care.',
    source_organisation: 'Central Statistics Office',
    source_title: 'Business in Ireland 2025 — Labour Market and Social Sustainability',
    source_url: 'https://www.cso.ie/',
    publication_date: '2025-06-15',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Demonstrates deep concentration of Indian workers specifically in public hospital and clinical roles.',
  },
  csep_processing_position: {
    id: 'dete_csep_processing_date_2026',
    metric: 'Critical Skills Employment Permit Queue Position',
    value: '25 September 2026',
    displayValue: '25 Sept 2026',
    unit: 'applications received date',
    period: 'Snapshot as of 2 October 2026',
    population_definition: 'Oldest applications currently being evaluated by DETE Employment Permits section.',
    source_organisation: 'Department of Enterprise, Tourism and Employment',
    source_title: 'Current Processing Dates for Employment Permits',
    source_url: 'https://www.enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/',
    publication_date: '2026-10-02',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Turnaround is approximately 1 week from submission to permit determination.',
  },
  join_family_cat_b_position: {
    id: 'isd_join_family_b_processing_date_2026',
    metric: 'Join Family (Category B — CSEP/Hosting) Queue Position',
    value: '28 June 2024',
    displayValue: '28 June 2024',
    unit: 'applications received date',
    period: 'Snapshot as of 29 September 2026',
    population_definition: 'Date of Join Family Category B applications currently being examined by Immigration Service Delivery.',
    source_organisation: 'Immigration Service Delivery (ISD)',
    source_title: 'Visa Decisions and Processing Dates',
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    publication_date: '2026-09-29',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Applications being processed are over 2 years and 3 months old (approx. 823 calendar days old).',
  },
  join_family_cat_a_position: {
    id: 'isd_join_family_a_processing_date_2026',
    metric: 'Join Family (Category A — Irish Citizen Sponsor) Queue Position',
    value: '4 July 2024',
    displayValue: '4 July 2024',
    unit: 'applications received date',
    period: 'Snapshot as of 29 September 2026',
    population_definition: 'Date of Join Family Category A applications currently being examined by ISD.',
    source_organisation: 'Immigration Service Delivery (ISD)',
    source_title: 'Visa Decisions and Processing Dates',
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    publication_date: '2026-09-29',
    last_checked: '2026-10-04',
    status: 'VERIFIED — PRIMARY SOURCE',
    notes: 'Queue age represents applications received up to 4 July 2024.',
  }
};

export const PROCESSING_SNAPSHOT_HISTORY: ProcessingDateSnapshot[] = [
  {
    id: 'snap-2026-06-30-cat-b',
    category: 'JOIN_FAMILY_CAT_B',
    category_label: 'Join Family — Category B (CSEP)',
    source: 'Immigration Service Delivery',
    snapshot_date: '2026-06-30',
    applications_processing_date: '2024-05-15',
    calculated_queue_age_days: 776,
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    notes: 'Official Tuesday update'
  },
  {
    id: 'snap-2026-07-28-cat-b',
    category: 'JOIN_FAMILY_CAT_B',
    category_label: 'Join Family — Category B (CSEP)',
    source: 'Immigration Service Delivery',
    snapshot_date: '2026-07-28',
    applications_processing_date: '2024-05-28',
    calculated_queue_age_days: 791,
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    notes: 'In 28 calendar days, queue advanced 13 application days.'
  },
  {
    id: 'snap-2026-08-25-cat-b',
    category: 'JOIN_FAMILY_CAT_B',
    category_label: 'Join Family — Category B (CSEP)',
    source: 'Immigration Service Delivery',
    snapshot_date: '2026-08-25',
    applications_processing_date: '2024-06-12',
    calculated_queue_age_days: 804,
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    notes: 'In 28 calendar days, queue advanced 15 application days.'
  },
  {
    id: 'snap-2026-09-29-cat-b',
    category: 'JOIN_FAMILY_CAT_B',
    category_label: 'Join Family — Category B (CSEP)',
    source: 'Immigration Service Delivery',
    snapshot_date: '2026-09-29',
    applications_processing_date: '2024-06-28',
    calculated_queue_age_days: 823,
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    notes: 'In 35 calendar days, queue advanced 16 application days. The backlog expanded in calendar time.'
  }
];

export const EVIDENCE_SOURCES: EvidenceSource[] = [
  {
    id: 'src-cso-2025',
    title: 'Business in Ireland 2025 — Labour Market and Social Sustainability',
    organisation: 'Central Statistics Office (CSO)',
    date: '2025',
    category: 'CSO Labour Statistics',
    last_checked: '2026-10-04',
    source_url: 'https://www.cso.ie/',
    data_used_on_site: '697,219 non-Irish employments (27.5%), 61.4% employment growth share (2019-2024), sector dependencies (Admin 45.6%, Hospitality 45.1%, ICT 41.4%), Indian workforce share (3.1% overall, 32.2% in Health).',
    definition: 'Payroll employments active in Ireland by self-declared nationality in administrative records.',
    methodology_notes: 'All figures refer to non-Irish nationality, not non-EU status. Double employments counted separately.'
  },
  {
    id: 'src-doh-2025',
    title: 'National Healthcare Statistics 2025 (Reference Year 2024)',
    organisation: 'Department of Health',
    date: '2025',
    category: 'Healthcare Workforce',
    last_checked: '2026-10-04',
    source_url: 'https://www.gov.ie/en/organisation/department-of-health/',
    data_used_on_site: '76,558 practising nurses; 54.0% first qualified outside Ireland. 20,961 practising physicians; 41.3% first qualified outside Ireland.',
    definition: 'Actively registered practitioners in the Republic of Ireland cross-referenced with educational source registry.',
    methodology_notes: 'Tracks location of first professional qualification. Not identical to nationality or current citizenship.'
  },
  {
    id: 'src-isd-dates-2026',
    title: 'Current Processing Dates for Long Stay D Visa & Join Family',
    organisation: 'Immigration Service Delivery (ISD), Department of Justice',
    date: '2026-09-29',
    category: 'Immigration Processing',
    last_checked: '2026-10-04',
    source_url: 'https://www.irishimmigration.ie/current-processing-dates/',
    data_used_on_site: 'Join Family Category B: applications from 28 June 2024 under review. Category A: 4 July 2024.',
    definition: 'The date on which the oldest unprocessed complete application file in each category was received by the Dublin Visa Office.',
    methodology_notes: 'Updated every Tuesday. Reflects queue front-line position, not a statistical average processing time.'
  },
  {
    id: 'src-dete-permits-2026',
    title: 'Employment Permits Weekly Processing Dashboard & Salary Thresholds',
    organisation: 'Department of Enterprise, Tourism and Employment (DETE)',
    date: '2026-10-02',
    category: 'Employment Permits',
    last_checked: '2026-10-04',
    source_url: 'https://www.enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/',
    data_used_on_site: 'Critical Skills EP processing 25 Sept 2026. General EP processing 26 August 2026. Salary thresholds: GEP €36,605; Care €32,691; CSEP ~€40,909.',
    definition: 'Target and actual processing dates for work permit applications across Irish enterprise categories.',
    methodology_notes: 'Permits handled by DETE, while subsequent visas and family permits handled separately by ISD.'
  },
  {
    id: 'src-isd-policy-2026',
    title: 'Policy Document on Non-EEA Family Reunification (Consolidated)',
    organisation: 'Immigration Service Delivery (ISD)',
    date: '2026-06-12',
    category: 'Immigration Policy',
    last_checked: '2026-10-04',
    source_url: 'https://www.irishimmigration.ie/coming-to-join-family-in-ireland/',
    data_used_on_site: 'Policy amended 26 Nov 2025 and 12 June 2026. Category A income requirement: €75,000 cumulative over preceding 3 years (avg €25,000/yr). Category C rules apply to GEP and Stamp 4 independent holders.',
    definition: 'Ministerial guidelines setting mandatory eligibility criteria, waiting periods, and income thresholds for non-EEA family reunification.',
    methodology_notes: 'Administrative scheme operating under ministerial discretion; not primary legislation.'
  }
];

export const CORRECTIONS_LOG: CorrectionEntry[] = [
  {
    id: 'corr-001',
    date: '2026-10-02',
    title: 'Employment Permit Processing Dates Updated',
    category: 'Processing Date',
    description: 'Updated DETE processing positions to reflect 2 October 2026 weekly snapshot (Critical Skills advancing to 25 September 2026 submissions).',
    previous_version: 'CSEP processing position: 18 September 2026.',
    updated_version: 'CSEP processing position: 25 September 2026.'
  },
  {
    id: 'corr-002',
    date: '2026-09-29',
    title: 'Join Family Category B & A Queue Dates Recorded',
    category: 'Processing Date',
    description: 'ISD weekly Tuesday update recorded. Category B advanced from 21 June 2024 to 28 June 2024.',
    previous_version: 'Category B position: 21 June 2024.',
    updated_version: 'Category B position: 28 June 2024.'
  },
  {
    id: 'corr-003',
    date: '2026-06-12',
    title: 'Family Reunification Category A Threshold Revision',
    category: 'Policy Threshold',
    description: 'Recorded the Department of Justice ministerial amendment replacing prior thresholds with €75,000 cumulative 3-year gross income for Irish citizen sponsors.',
    previous_version: 'Prior threshold required €40,000 cumulative over 3 years.',
    updated_version: 'New threshold requires €75,000 cumulative over 3 years (€25k/yr avg).'
  }
];

export const VERIFIED_CITIZEN_CASES: CitizenCase[] = [
  {
    id: 'case-00142',
    public_case_id: 'IRR-2026-000142',
    created_at: '2026-09-12',
    updated_at: '2026-10-01',
    category: 'Join Family Delay',
    subcategory: 'Category B Spouse & Children',
    short_title: 'HSE Staff Nurse — Spouse and Two Children Awaiting Visa',
    public_summary: 'A critical care nurse working in a Dublin public hospital on a Critical Skills permit submitted Join Family applications for their spouse and two minor children in August 2024. As of October 2026, the file remains unprocessed in the queue.',
    sponsor_category: 'B',
    immigration_permission: 'Stamp 1 (Critical Skills Employment Permit)',
    application_date: '2024-08-14',
    problem_start_date: '2024-08-14',
    county_public: 'Dublin',
    children_count: 2,
    children_involved: true,
    irish_citizen_child: false,
    waiting_days: 782,
    authority: 'Immigration Service Delivery / Dublin Visa Office',
    current_status: 'unresolved',
    verification_status: 'documented_case',
    publication_status: 'published',
    anonymous_preference: 'ANONYMOUS',
    evidence_summary: 'VFS Global receipt, AVATS application summary, employment contract with Dublin hospital reviewed and verified.'
  },
  {
    id: 'case-00089',
    public_case_id: 'IRR-2026-000089',
    created_at: '2026-08-04',
    updated_at: '2026-09-20',
    category: 'Child Ageing Out (Age-Lock)',
    subcategory: 'Dependent Child turned 18 during delay',
    short_title: 'Daughter Turned 18 During 19-Month Administrative Wait',
    public_summary: 'An IT architect legally resident in Galway lodged an application for their dependent daughter when she was 16 years and 11 months old. Following a 19-month processing backlog, the visa office issued an inquiry regarding adult independent status.',
    sponsor_category: 'B',
    immigration_permission: 'Stamp 4',
    application_date: '2024-02-10',
    problem_start_date: '2025-02-10',
    county_public: 'Galway',
    children_count: 1,
    children_involved: true,
    irish_citizen_child: false,
    waiting_days: 967,
    authority: 'Immigration Service Delivery',
    current_status: 'unresolved',
    verification_status: 'documented_case',
    publication_status: 'published',
    anonymous_preference: 'FIRST NAME / INITIAL',
    evidence_summary: 'AVATS filing date confirms minor status at lodging; correspondence logs verify absence of interim procedural updates.'
  },
  {
    id: 'case-00043',
    public_case_id: 'IRR-2026-000043',
    created_at: '2026-07-15',
    updated_at: '2026-09-25',
    category: 'IRP Expiry & Travel Barrier',
    subcategory: 'Immigration Continuity Gap',
    short_title: 'Hospital Doctor Trapped Abroad During Family Emergency',
    public_summary: 'A Non-Consultant Hospital Doctor in Cork applied for Stamp 4 renewal 10 weeks prior to expiry. While waiting through an 18-week backlog, the doctor travelled abroad for an urgent bereavement and faced entry complications upon return due to lack of bridging documentation.',
    sponsor_category: 'Unknown',
    immigration_permission: 'Stamp 4 Renewal Pending',
    application_date: '2025-11-04',
    problem_start_date: '2026-01-15',
    county_public: 'Cork',
    children_count: 1,
    children_involved: true,
    irish_citizen_child: true,
    waiting_days: 334,
    authority: 'Registration Office / Border Management Unit',
    current_status: 'resolved',
    verification_status: 'documented_case',
    publication_status: 'published',
    anonymous_preference: 'ANONYMOUS',
    evidence_summary: 'ISD renewal application confirmation, travel itinerary, hospital HR letters verified.'
  },
  {
    id: 'case-00201',
    public_case_id: 'IRR-2026-000201',
    created_at: '2026-09-20',
    updated_at: '2026-10-02',
    category: 'Family Income Threshold Barrier',
    subcategory: 'Healthcare Assistant (General Permit)',
    short_title: 'Elder Care Specialist Barred by Single-Income Rule',
    public_summary: 'A certified healthcare assistant working in a residential nursing home earning €32,691 annually cannot sponsor their spouse due to Category C income guidelines and the explicit bar against combining prospective spousal earnings.',
    sponsor_category: 'C',
    immigration_permission: 'General Employment Permit',
    application_date: '2025-05-18',
    problem_start_date: '2025-05-18',
    county_public: 'Limerick',
    children_count: 0,
    children_involved: false,
    irish_citizen_child: false,
    waiting_days: 504,
    authority: 'Immigration Service Delivery',
    current_status: 'unresolved',
    verification_status: 'documented_case',
    publication_status: 'published',
    anonymous_preference: 'ANONYMOUS',
    evidence_summary: 'Employment permit documents, employment contract, ISD formal rejection notice on threshold grounds.'
  }
];
